services:
  web:
    env_file:
      - apps/.env
    build: .
    command: python /code/apps/manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=conf.settings.prod